apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-env-deployment
  namespace: demo-configmap-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-deployment
  template:
    metadata:
      labels:
        app: lab-deployment
    spec:
      containers:
        - name: lab-deployment
          image: darshanadinushal/helloworldapp:3.3
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: env-service
  namespace: demo-configmap-env
spec:
  selector:
    app: lab-deployment
  ports:
    - port: 80
      targetPort: 80

     
      